MyBlog.WebUI/Models/Portfolio/PortfolioViewModel.cs
using MyBlog.WebUI.Entity;
using MyBlog.WebUI.Util;
using System.ComponentModel.DataAnnotations;

namespace MyBlog.WebUI.Models.Portfolio
{
    public class PortfolioViewModel
    {

        public int Id { get; set; }

        [Required]
        public string Title { get; set; } = null!;

        [Required]
        public int PortfolioType { get; set; }

        [Required]
        public string ProjectDate { get; set; } = null!;
        public string? ProjectUrl { get; set; }
        public string UsedTechnologies { get; set; } = null!;
        public string? Description { get; set; }

        public int DisplayOrder { get; set; }


        public List<int> enumAppTypeList=> Enum.GetValues(typeof(Enums.AppType))
                                       .Cast<int>()
                                       .ToList();

        public List<ProjectImage>? ProjectImages { get; set; }
    }
}

MyBlog.WebUI/Controllers/PortfolioController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog.WebUI.DataAccess.Abstract;
using MyBlog.WebUI.Entity;
using MyBlog.WebUI.Models.Portfolio;
using MyBlog.WebUI.Util;
using MyBlog.WebUI.Util.Abstract;
using System.Data;

namespace MyBlog.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class PortfolioController : Controller
    {
        private readonly IPortfolioDal _portfolioDal;
        private readonly IMethods _methods;
        private readonly IProjectImageDal _projectImageDal;
        private readonly IMapper _mapper;

        public PortfolioController(IPortfolioDal portfolioDal, IMethods methods, IProjectImageDal projectImageDal, IMapper mapper)
        {
            _portfolioDal = portfolioDal;
            _methods = methods;
            _projectImageDal = projectImageDal;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()//admin Index
        {
            var portfolios = await _portfolioDal.GetPortfolios();

            if (portfolios == null)
                return NotFound();

            return View(portfolios);
        }

        public async Task<IActionResult> CreateProject()
        {
            return View(new PortfolioViewModel { });
        }

        [HttpPost]
        public async Task<IActionResult> CreateProject(PortfolioViewModel model /*int[] appTypeIds*/)
        {
            List<ProjectImage> images = new List<ProjectImage>();

            if (ModelState.IsValid)
            {
                var portfolio=_mapper.Map<Portfolio>(model);

                await _portfolioDal.CreateAsync(portfolio);

                return RedirectToAction("EditProject", new { id = portfolio.Id });
            }

            return View(model);
        }

        [HttpPost]
        public async Task<JsonResult> AddImageForPortfolio(IFormFile ImageFile, int PortfolioId, bool IsDefault)
        {
            List<string> allErrors = new List<string>();
            bool valid = false;
            ProjectImage image = new ProjectImage();

            if (PortfolioId == 0)
            {
                allErrors.Add("Portfolio is not found");

                return Json(new
                {
                    IsValid = valid,
                    ErrorMessages = allErrors
                });
            }

            var imageFileModel = await _methods.CreateImageFileAsync(ImageFile, (int)Enums.ImageType.Portfolio);
            if (!imageFileModel.IsValid)
                allErrors.Add(imageFileModel.ErrorString);
            else
            {
                image.PortfolioId = PortfolioId;
                image.ImageUrl = imageFileModel.ImageCreatedName;

                if (IsDefault)
                {
                    await _portfolioDal.ResetPortfolioImagesIsCover(PortfolioId);
                    image.IsCoverImage = true;
                }

                await _projectImageDal.CreateAsync(image);

                valid = true;

                return Json(new
                {
                    IsValid = valid,
                    ErrorMessages = allErrors,
                });

            }

            return Json(new
            {
                IsValid = valid,
                ErrorMessages = allErrors
            });
        }

        [HttpPost]
        public async Task<JsonResult> DeleteImageFromPortfolio(int ImageId)
        {
            bool isValid = false;
            try
            {
                string[] fileNames = new string[1];
                var portImage = await _projectImageDal.GetById(ImageId);
                await _projectImageDal.DeleteAsync(portImage);
                fileNames[0] = portImage.ImageUrl;
                await _methods.DeletePortfolioImage(fileNames);
                isValid = true;
            }
            catch (Exception)
            {

            }

            return Json(new
            {
                IsValid = isValid,
                ErrorMessage = "Error !"
            });
        }


        [HttpPost]
        public async Task<JsonResult> DeletePortfolio(int PortfolioId)
        {
            bool valid = false;

            try
            {
                if (PortfolioId != 0)
                {
                    var portf = await _portfolioDal.GetPortfolioById(PortfolioId);
                    await _portfolioDal.DeletePortfolioWithImages(portf.Id);
                    await _methods.DeletePortfolioImage(portf.ProjectImages.Select(x => x.ImageUrl).ToArray());
                    valid = true;
                }
            }
            catch (Exception)
            {
                //log error
            }

            return Json(new
            {
                IsValid = valid,
                ErrorMessage = "Error !!",
            });
        }

        public async Task<IActionResult> EditProject(int id)
        {
            if (id == 0) return NotFound();

            var portfolio = await _portfolioDal.GetPortfolioById(id);

            var viewModel = _mapper.Map<PortfolioViewModel>(portfolio);

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditProject(PortfolioViewModel model)
        {
            if (ModelState.IsValid)
            {
                var portfolio = await _portfolioDal.GetPortfolioById(model.Id);
                var oldImages = portfolio.ProjectImages;



                if (portfolio == null) return NotFound();

                //_mapper.Map<Portfolio>(model);
                _mapper.Map(model, portfolio);
                portfolio.ProjectImages = oldImages;
                await _portfolioDal.UpdateAsync(portfolio);

            }
            return RedirectToAction("Index");
        }

        public async Task<JsonResult> SetImageToCover(int ImageId,int PortfolioId)
        {
            bool isValid = false;
            string errorMessage = "";

            if (ImageId == 0 || PortfolioId == 0)
                errorMessage = "wrong match";
            try
            {
                await _portfolioDal.ResetPortfolioImagesIsCover(PortfolioId);
                var image = await _projectImageDal.GetById(ImageId);
                image.IsCoverImage = true;
                await _projectImageDal.UpdateAsync(image);
                isValid=true;

                return Json(new
                {
                    IsValid = isValid,
                    ErrorMessage = "",
                });
            }
            catch (Exception)
            {
                isValid = false;
                errorMessage = "Error Happened";
            }

            return Json(new
            {
                IsValid = isValid,
                ErrorMessage = errorMessage,
            });

        }

        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            var portfolio = await _portfolioDal.GetPortfolioById(id);

            if(portfolio == null)
                return NotFound();

            return View(portfolio);
        }
    }
}

MyBlog.WebUI/Views/Portfolio/CreateProject.cshtml
@model MyBlog.WebUI.Models.Portfolio.PortfolioViewModel

@{
    ViewData["Title"] = "ExperienceEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="main__title">
            <h2>Create Exp (Edit)</h2>
        </div>
    </div>
    <div class="col-12">
        <form asp-controller="Portfolio" asp-action="CreateProject" method="post" class="form" novalidate>
            <div asp-validation-summary="ModelOnly" class="model-danger"></div>
            <div class="row row--form">
                <div class="col-12 col-md-7 form__content">
                    <div class="row row--form">
                        <div class="col-12">
                            <label asp-for="Title" class="form__label"></label>
                            <input asp-for="Title" class="form__input" placeholder="Title Giriniz">
                            <span asp-validation-for="Title" class="model-danger"></span>
                        </div>

                        <div class="col-12">
                            <label asp-for="ProjectDate" class="form__label"></label>
                            <input asp-for="ProjectDate" class="form__input">
                            <span asp-validation-for="ProjectDate" class="model-danger"></span>
                        </div>
                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="ProjectUrl" class="form__label"></label>
                            <input asp-for="ProjectUrl" class="form__input">
                            <span asp-validation-for="ProjectUrl" class="model-danger"></span>
                        </div>

                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="UsedTechnologies" class="form__label"></label>
                            <input asp-for="UsedTechnologies" class="form__input">
                            <span asp-validation-for="UsedTechnologies" class="model-danger"></span>
                        </div>

                        <div class="col-12">
                            <label asp-for="Description" class="form__label"></label>
                            <textarea asp-for="Description" class="form__textarea" placeholder=""></textarea>
                            <span asp-validation-for="Description" class="model-danger"></span>
                        </div>

                        <div class="col-12">
                            @if (Model.Id > 0)
                            {
                                <label asp-for="ProjectImages" class="form__label"></label>
                                <a href="#modal-add-image" class="main__title-link opening_modal_add open-modal ml-0 mb-3">Add Image</a>

                                <div class="profile__content">
                                    <div class="profile__user">
                                        <div class="profile__avatar">
                                            <img src="img/user.svg" alt="">
                                        </div>
                                        <div class="profile__meta profile__meta--green">

                                            <span>HotFlix ID: 23562</span>
                                        </div>
                                    </div>

                                    <div class="profile__mobile-tabs" id="profile__mobile-tabs">
                                        <div class="profile__mobile-tabs-btn dropdown-toggle" role="navigation" id="mobile-tabs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <input type="button" value="Profile">
                                            <span></span>
                                        </div>

                                        <div class="profile__mobile-tabs-menu dropdown-menu" aria-labelledby="mobile-tabs">
                                            <ul class="nav nav-tabs" role="tablist">
                                                <li class="nav-item" data-value="profile"><a class="nav-link active" id="1-tab" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">Profile</a></li>

                                                <li class="nav-item" data-value="comments"><a class="nav-link" id="2-tab" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">Comments</a></li>

                                                <li class="nav-item" data-value="reviews"><a class="nav-link" id="3-tab" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">Reviews</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="profile__actions">
                                        <a href="#modal-status3" class="profile__action profile__action--banned open-modal"><i class="icon ion-ios-lock"></i></a>
                                        <a href="#modal-delete3" class="profile__action profile__action--delete open-modal"><i class="icon ion-ios-trash"></i></a>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <h2 style="color: #f9ab00;">To add images, first create a portfolio</h2>
                            }


                        </div>
                        <div class="col-12">
                            <label asp-for="PortfolioType" class="form__label"></label>
                            <select class="js-example-basic-single" asp-for="PortfolioType">

                                <option value=""></option>
                                @foreach (var appType in Model.enumAppTypeList)
                                {
                                    <option value="@appType">@Enum.GetName(typeof(Enums.AppType), appType)</option>
                                }

                            </select>
                        </div>
                    </div>
                </div>

                <div class="col-12">
                    <button type="submit" class="form__btn">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{

    <environment names="Development">
        <script src="portfolio-create" debug="true"></script>
    </environment>

    <environment names="Production">
        <script src="portfolio-create"></script>
    </environment>
}

MyBlog.WebUI/Views/Portfolio/EditProject.cshtml
@model MyBlog.WebUI.Models.Portfolio.PortfolioViewModel

@{
    ViewData["Title"] = "PortfolioEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="main__title">
            <h2>Create Portfolio (Edit)</h2>
        </div>
    </div>

    <div class="col-12">
        <form asp-controller="Portfolio" asp-action="EditProject" method="post" class="form" novalidate>
            <div asp-validation-summary="ModelOnly" class="model-danger"></div>
            <input asp-for="Id" type="hidden" class="portfId" />
            <div class="row row--form">
                <div class="col-12 col-md-7 form__content">
                    <div class="row row--form">
                        <div class="col-12">
                            <label asp-for="Title" class="form__label"></label>
                            <input asp-for="Title" class="form__input">
                            <span asp-validation-for="Title" class="model-danger"></span>
                        </div>

                        <div class="col-12">
                            <label asp-for="ProjectDate" class="form__label"></label>
                            <input asp-for="ProjectDate" class="form__input">
                            <span asp-validation-for="ProjectDate" class="model-danger"></span>
                        </div>
                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="ProjectUrl" class="form__label"></label>
                            <input asp-for="ProjectUrl" class="form__input">
                            <span asp-validation-for="ProjectUrl" class="model-danger"></span>
                        </div>

                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="UsedTechnologies" class="form__label"></label>
                            <input asp-for="UsedTechnologies" class="form__input">
                            <span asp-validation-for="UsedTechnologies" class="model-danger"></span>
                        </div>

                        <div class="col-12">
                            <label asp-for="Description" class="form__label"></label>
                            <textarea asp-for="Description" class="form__textarea" placeholder=""></textarea>
                            <span asp-validation-for="Description" class="model-danger"></span>
                        </div>

                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="DisplayOrder" class="form__label"></label>
                            <input asp-for="DisplayOrder" type="number" min="1" class="form__input" placeholder="DisplayOrder">
                            <span asp-validation-for="DisplayOrder" class="model-danger"></span>
                        </div>

                        <div class="col-12">
                            @if (Model.Id > 0)
                            {
                                <label asp-for="ProjectImages" class="form__label"></label><a href="#modal-add-image" class="main__title-link opening_modal_add open-modal ml-0 mb-3">Add Image</a>

                                if (Model.ProjectImages?.Count > 0)
                                {
                                    foreach (var item in Model.ProjectImages)
                                    {
                                        <div class="profile__content">
                                            <div class="profile__user">
                                                <div class="profile__avatar">
                                                    <img src="~/img/portfoliopicture/@item.ImageUrl" alt="">
                                                </div>
                                                <div class="profile__meta profile__meta--green">

                                                    <span>Image Name:@item.ImageUrl</span>
                                                </div>
                                            </div>

                                            <div class="profile__actions">
                                                <a href="#" onclick="SetCoverImage(this)" id="@item.Id" data-pid="@item.PortfolioId" class="main__title-link opening_modal_add open-modal btn-sm mr-2" style="border: 2px solid #00f941 !important;">Set Cover Image</a>
                                                <a href="#modal-delete" id="@item.Id" class="profile__action profile__action--delete open-modal opening_modal_delete"><i class="icon ion-ios-trash"></i></a>
                                            </div>
                                        </div>
                                    }
                                }

                            }
                            else
                            {
                                <h2>Resim eklemek için ilk önce portfolio olustur</h2>
                            }


                        </div>
                        <div class="col-12">
                            <label asp-for="PortfolioType" class="form__label"></label>
                            <select class="js-example-basic-single" asp-for="PortfolioType">

                                <option value=""></option>
                                @foreach (var appType in Model.enumAppTypeList)
                                {
                                    <option value="@appType">@Enum.GetName(typeof(Enums.AppType), appType)</option>
                                }

                            </select>
                        </div>
                    </div>
                </div>

                <div class="col-12">
                    <button type="submit" class="form__btn">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div id="modal-add-image" class="zoom-anim-dialog mfp-hide modal">
    <h6 class="modal__title">Add Image</h6>
    <form action="/" method="post">
        <div id="add-image-error" class="model-danger"></div>
        <label asp-for="ProjectImages" class="form__label"></label>
        <div class="form__gallery">
            <label id="gallery1" for="imageInput">Upload photos</label>
            <input data-name="#gallery1" id="imageInput" name="gallery" class="form__gallery-upload" type="file" accept=".png, .jpg, .jpeg" multiple="">
        </div>

        <div class="sign__group sign__group--checkbox">
            <input value="" id="checkBoxInput" type="checkbox">
            <label for="checkBoxInput">Varsayılan resim oalrak ayarla(Kapak Resmi)</label>
        </div>

        <span class="d-none" id="spinner">
            <img style="width:20px" src="~/loading_gif.webp" />
        </span>
        <div class="modal__btns">
            <button id="imageAdd" class="modal__btn modal__btn--apply" type="button">Save</button>
            <button id="educateAddDismiss" class="modal__btn modal__btn--dismiss eduDissmisClick" type="button">Dismiss</button>
        </div>
    </form>

</div>

<!-- modal delete -->
<div id="modal-delete" class="zoom-anim-dialog mfp-hide modal">
    <h6 class="modal__title">Image delete</h6>
    <div id="delete-exp-error">
    </div>
    <p class="modal__text">Are you sure to permanently delete this image?</p>

    <div class="modal__btns">
        <button id="portfolioImageDelete" class="modal__btn modal__btn--apply" type="button">Delete</button>
        <button class="modal__btn modal__btn--dismiss skillDissmisClick" type="button">Dismiss</button>
    </div>
</div>
<!-- end modal delete -->


@section Scripts {

    <environment names="Development">
        <script src="portfolio-edit" debug="true"></script>
    </environment>

    <environment names="Production">
        <script src="portfolio-edit"></script>
    </environment>

}

MyBlog.WebUI/Views/Portfolio/Index.cshtml
@model List<MyBlog.WebUI.Entity.Portfolio>

@{
    ViewData["Title"] = "PortfoliosEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="main__title">
            <h2>Portfolios (Edit)</h2>
        </div>
    </div>

    <div class="col-12">
        <form action="edit" method="post" class="form" enctype="multipart/form-data" novalidate>
            <div asp-validation-summary="ModelOnly" class="model-danger"></div>
            <input type="hidden" />
            <div class="row row--form">
                <div class="col-12 col-md-7 form__content">
                    <h4 class="form__title">Portfolios</h4>
                    <a asp-controller="Portfolio" asp-action="CreateProject" class="form__btn ml-0 mb-3">Add Project</a>
                    <div class="main__table-wrap mCustomScrollbar _mCS_2 mCS_no_scrollbar" style="overflow: visible;">
                        <div id="mCSB_2" class="mCustomScrollBox mCS-custom-bar2 mCSB_horizontal mCSB_outside" tabindex="0" style="max-height: none;">
                            <div id="mCSB_2_container" class="mCSB_container mCS_x_hidden mCS_no_scrollbar_x" style="position: relative; top: 0px; left: 0px; width: 1051px; min-width: 100%; overflow-x: inherit;" dir="ltr">
                                <table class="main__table">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Date</th>
                                            <th>DisplayOrder</th>
                                            <th>ACTIONS</th>
                                        </tr>
                                    </thead>

                                    <tbody id="eduTbody">
                                        @foreach (var project in Model)
                                        {

                                            <tr id="tr_@project.Id">

                                                <td>
                                                    <div class="main__table-text">@project.Id</div>
                                                </td>
                                                <td>
                                                    <div class="main__table-text">@project.Title</div>
                                                </td>
                                                <td>
                                                    <div class="main__table-text">@project.ProjectDate</div>
                                                </td>
                                                <td>
                                                    <div class="main__table-text">@project.DisplayOrder</div>
                                                </td>
                                                <td>
                                                    <div class="main__table-btns">
                                                        <a asp-controller="Portfolio" asp-action="EditProject" asp-route-id="@project.Id" class="main__table-btn main__table-btn--edit ">
                                                            <i class="icon ion-ios-create "></i>
                                                        </a>
                                                        <a href="#modal-delete" id="@project.Id" class="main__table-btn main__table-btn--delete opening_modal_delete open-modal">
                                                            <i class="icon ion-ios-trash"></i>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        }


                                    </tbody>
                                </table>
                            </div>
                        </div><div id="mCSB_2_scrollbar_horizontal" class="mCSB_scrollTools mCSB_2_scrollbar mCS-custom-bar2 mCSB_scrollTools_horizontal" style="display: none;"><div class="mCSB_draggerContainer"><div id="mCSB_2_dragger_horizontal" class="mCSB_dragger" style="position: absolute; min-width: 30px; width: 0px; left: 0px;"><div class="mCSB_dragger_bar"></div><div class="mCSB_draggerRail"></div></div></div></div>
                    </div>
                </div>

            </div>
        </form>
    </div>
    <!-- modal delete -->
    <div id="modal-delete" class="zoom-anim-dialog mfp-hide modal">
        <h6 class="modal__title">Portfolio delete</h6>
        <div id="delete-exp-error">
        </div>
        <p class="modal__text">Are you sure to permanently delete this portfolio?</p>

        <div class="modal__btns">
            <button id="portfolioDelete" class="modal__btn modal__btn--apply" type="button">Delete</button>
            <button class="modal__btn modal__btn--dismiss skillDissmisClick" type="button">Dismiss</button>
        </div>
    </div>
    <!-- end modal delete -->

</div>

@section Scripts{
    <environment names="Development">
        <script src="portfolio-index" debug="true"></script>
    </environment>

    <environment names="Production">
        <script src="portfolio-index"></script>
    </environment>

}