MyBlog.WebUI/Models/Resume/EditEducationViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyBlog.WebUI.Models.Resume
{
    public class EditEducationViewModel
    {
        public int EducationId { get; set; }
        [Required]
        public string? Title { get; set; }
        [Required]
        public string? DateBetween { get; set; }
        [Required]
        public string? Adress { get; set; }
        [Required]
        public string? UniversityName { get; set; }
        public string? Description { get; set; }
    }
}

MyBlog.WebUI/Models/Resume/ExperienceViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyBlog.WebUI.Models.Resume
{
    public class ExperienceViewModel
    {
        public int Id { get; set; }

        [Required]
        public string? Title { get; set; }

        [Required]
        public string? DateBetween { get; set; }

        [Required]
        public string? Adress { get; set; }

        public string? Description { get; set; }

        [Required]
        public string? CompanyName { get; set; }

        public int DisplayOrder { get; set; }

        public string? ExperienceSteps { get; set; }

    }
}

MyBlog.WebUI/Models/Resume/ResumeViewModel.cs
using MyBlog.WebUI.Entity;

namespace MyBlog.WebUI.Models.Resume
{
    public class ResumeViewModel
    {
        public List<Education> Educations{ get; set; } = new List<Education>();
        public List<Experience> Experiences { get; set; }= new List<Experience>();
        public About? About { get; set; }
    }
}

MyBlog.WebUI/Controllers/ResumeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog.WebUI.DataAccess.Abstract;
using MyBlog.WebUI.Entity;
using MyBlog.WebUI.Models.Resume;
using MyBlog.WebUI.Util.Abstract;
using System.Data;

namespace MyBlog.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class ResumeController : Controller
    {
        private readonly IEducationDal _educationDal;
        private readonly IMethods _methods;
        private readonly IExperienceDal _experienceDal;
        private readonly IMapper _mapper;
        public ResumeController(IEducationDal educationDal, IMethods methods, IExperienceDal experienceDal, IMapper mapper)
        {
            _educationDal = educationDal;
            _methods = methods;
            _experienceDal = experienceDal;
            _mapper = mapper;
        }

        public async Task<IActionResult> Education()
        {
            ResumeViewModel model = new ResumeViewModel();
            model.Educations = _educationDal.GetAll().ToList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateEducation(EditEducationViewModel model)
        {
            Education educationToAdd = new Education();
            List<string> allErrors = new List<string>();
            bool valid = false;
            if (!ModelState.IsValid)
            {
                allErrors = _methods.ModelErrors(ModelState);
            }
            else
            {
                educationToAdd=_mapper.Map<Education>(model);
                educationToAdd = await _educationDal.CreateAsync(educationToAdd);
                valid = true;
            }

            return Json(new
            {
                IsValid = valid,
                ErrorMessages = allErrors,
                Education = educationToAdd
            });
        }

        [HttpPost]
        public async Task<JsonResult> EditEducation(EditEducationViewModel model)
        {
            List<string> allErrors = new List<string>();
            Education eduCallback = new Education();
            bool valid = false;
            if (!ModelState.IsValid)
            {
                allErrors = _methods.ModelErrors(ModelState);
            }
            else
            {
                var skillToUpdateR = await _educationDal.GetById(model.EducationId);

                _mapper.Map(model, skillToUpdateR);

                eduCallback = await _educationDal.ReturnUpdateAsync(skillToUpdateR);
                valid = true;
            }
            return Json(new
            {
                IsValid = valid,
                ErrorMessages = allErrors,
                Education = eduCallback
            });

        }

        [HttpPost]
        public async Task<JsonResult> DeleteEducation(int EduId)
        {
            List<string> allErrors = new List<string>();
            bool valid = false;

            if (EduId == 0)
            {
                ModelState.AddModelError("", "Error");
                allErrors = _methods.ModelErrors(ModelState);
            }
            else
            {
                await _educationDal.DeleteAsync(await _educationDal.GetById(EduId));
                valid = true;
            }
            return Json(new
            {
                IsValid = valid,
                ErrorMessages = allErrors
            });
        }


        //-------------experience--------

        public async Task<IActionResult> Experiences()
        {

            var experiences = _experienceDal.GetAll().OrderBy(x=>x.DisplayOrder).Select(e =>
                new ExperienceViewModel
                {
                    Id = e.Id,
                    Title = e.Title,
                    DateBetween = e.DateBetween,
                    CompanyName = e.CompanyName,
                    Adress = e.Adress,
                    ExperienceSteps = e.ExperienceSteps,
                    DisplayOrder= e.DisplayOrder,
                    

                }).ToList();

            return View(experiences);
        }

        public async Task<IActionResult> CreateExperience()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateExperience(ExperienceViewModel model)
        {
            if (ModelState.IsValid)
            {
                var experience =_mapper.Map<Experience>(model);
                await _experienceDal.CreateAsync(experience);

                return RedirectToAction("Experiences");
            }

            return View(model);

        }

        public async Task<IActionResult> ExperienceEdit(int id)
        {
            if (id == 0)
                ModelState.AddModelError("", "Error ! Try Again");

            var experience = await _experienceDal.GetById(id);

            if (experience == null)
                ModelState.AddModelError("", "Error ! Try Again");
            else
            {
                var experienceModel = _mapper.Map<ExperienceViewModel>(experience);
                return View(experienceModel);
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ExperienceEdit(ExperienceViewModel model)
        {
            if (ModelState.IsValid)
            {
                var experience = await _experienceDal.GetById(model.Id);

                if (experience == null)
                {
                    ModelState.AddModelError("", "Error ! Try Again");
                    return View(experience);
                }
                else
                {
                    _mapper.Map(model,experience);
                    await _experienceDal.UpdateAsync(experience);

                    return RedirectToAction("Experiences");
                }


            }
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> DeleteExperience(int ExpId)
        {
            List<string> allErrors = new List<string>();
            bool valid = false;

            if (ExpId == 0)
            {
                ModelState.AddModelError("", "Error");
                allErrors = _methods.ModelErrors(ModelState);
            }
            else
            {
                await _experienceDal.DeleteAsync(await _experienceDal.GetById(ExpId));
                valid = true;
            }
            return Json(new
            {
                IsValid = valid,
                ErrorMessages = allErrors
            });
        }

    }
}

MyBlog.WebUI/Views/Resume/CreateExperience.cshtml
@model MyBlog.WebUI.Models.Resume.ExperienceViewModel

@{
    ViewData["Title"] = "ExperienceEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="main__title">
            <h2>Create Exp (Edit)</h2>
        </div>
    </div>

    <div class="col-12">
        <form asp-controller="Resume" asp-action="CreateExperience" method="post" class="form"  novalidate>
            <div asp-validation-summary="ModelOnly" class="model-danger"></div>
            <div class="row row--form">
                <div class="col-12 col-md-7 form__content">
                    <div class="row row--form">
                        <div class="col-12">
                            <label asp-for="Title" class="form__label"></label>
                            <input asp-for="Title" class="form__input" placeholder="Title Giriniz">
                            <span asp-validation-for="Title" class="model-danger"></span>
                        </div>

                        <div class="col-12">
                            <label asp-for="DateBetween" class="form__label"></label>
                            <input asp-for="DateBetween" class="form__input" placeholder="Hangi tarihler arasında">
                            <span asp-validation-for="DateBetween" class="model-danger"></span>
                        </div>
                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="CompanyName" class="form__label"></label>
                            <input asp-for="CompanyName" class="form__input" placeholder="Firma İsmi">
                            <span asp-validation-for="CompanyName" class="model-danger"></span>
                        </div>

                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="Adress" class="form__label"></label>
                            <input asp-for="Adress" class="form__input" placeholder="Adres">
                            <span asp-validation-for="Adress" class="model-danger"></span>
                        </div>

                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="DisplayOrder" class="form__label"></label>
                            <input asp-for="DisplayOrder" type="number" min="1" class="form__input" placeholder="DisplayOrder">
                            <span asp-validation-for="DisplayOrder" class="model-danger"></span>
                        </div>

                        <div class="col-12">
                            <label asp-for="ExperienceSteps" class="form__label"></label>
                            <textarea asp-for="ExperienceSteps" class="form__textarea" placeholder="Deneyim Adımları"></textarea>
                            <span asp-validation-for="ExperienceSteps" class="model-danger"></span>
                        </div>

                    </div>
                </div>

                <div class="col-12">
                    <button type="submit" class="form__btn">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

MyBlog.WebUI/Views/Resume/EditEducation.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <!-- main title -->
    <div class="col-12">
        <div class="main__title">
            <h2>Education (Edit)</h2>
        </div>
    </div>
    <!-- end main title -->
    <!-- form -->
    <div class="col-12">
        <form action="edit" method="post" class="form" enctype="multipart/form-data" novalidate>
            <div asp-validation-summary="ModelOnly" class="model-danger"></div>
            <input type="hidden" />
            <div class="row row--form">
                <div class="col-12 col-md-7 form__content">
                    <h4 class="form__title">Educations</h4>
                    <a href="#modal-add-education" class="main__title-link opening_modal_add open-modal ml-0 mb-3">Add Education</a>
                    <div class="main__table-wrap mCustomScrollbar _mCS_2 mCS_no_scrollbar" style="overflow: visible;">
                        <div id="mCSB_2" class="mCustomScrollBox mCS-custom-bar2 mCSB_horizontal mCSB_outside" tabindex="0" style="max-height: none;">
                            <div id="mCSB_2_container" class="mCSB_container mCS_x_hidden mCS_no_scrollbar_x" style="position: relative; top: 0px; left: 0px; width: 1051px; min-width: 100%; overflow-x: inherit;" dir="ltr">
                                <table class="main__table">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>University</th>
                                            <th>Order</th>
                                            <th>ACTIONS</th>
                                        </tr>
                                    </thead>

                                    <tbody id="skillTbody">
                                        @*@foreach (var skill in Model.Skills)
                                            {

                                            }*@
                                        <tr id="tr_">
                                            <td>
                                                <div class="main__table-text">12</div>
                                            </td>
                                            <td>
                                                <div id="" class="main__table-text">Bilgisayar Mühendisliği</div>
                                            </td>
                                            <td>
                                                <div id="" class="main__table-text">SDÜ</div>
                                            </td>
                                            <td>
                                                <div class="main__table-text">1</div>
                                            </td>

                                            <td>
                                                <div class="main__table-btns">
                                                    <a href="#modal-edit-skill" class="main__table-btn main__table-btn--edit opening_modal_edit open-modal">
                                                        <i class="icon ion-ios-create "></i>
                                                    </a>
                                                    <a href="#modal-delete" class="main__table-btn main__table-btn--delete opening_modal_delete open-modal">
                                                        <i class="icon ion-ios-trash"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div><div id="mCSB_2_scrollbar_horizontal" class="mCSB_scrollTools mCSB_2_scrollbar mCS-custom-bar2 mCSB_scrollTools_horizontal" style="display: none;"><div class="mCSB_draggerContainer"><div id="mCSB_2_dragger_horizontal" class="mCSB_dragger" style="position: absolute; min-width: 30px; width: 0px; left: 0px;"><div class="mCSB_dragger_bar"></div><div class="mCSB_draggerRail"></div></div></div></div>
                    </div>
                </div>
                @*<div class="col-12">
                        <button type="submit" class="form__btn">Save</button>
                    </div>*@
            </div>
        </form>
    </div>
    <!-- end form -->
    <!-- end modal view -->
    <!-- modal add -->
    <div id="modal-add-education" class="zoom-anim-dialog mfp-hide modal">
        <h6 class="modal__title">Add Education</h6>

        <label class="form__label">Title</label>
        <input id="Title" name="Title" class="form__input">

        <label class="form__label">DateBetween</label>
        <input id="DateBetween" name="DateBetween" class="form__input">

        <label class="form__label">University Name</label>
        <input id="UniversityName" name="UniversityName" class="form__input">

        <label class="form__label">Adress</label>
        <input id="Adress" name="Adress" class="form__input">

        <label class="form__label">Description</label>
        <input id="Description" name="Description" class="form__input">

        <div id="add-education-error">
        </div>
        <span class="d-none" id="spinner">
            <img style="width:20px" src="~/loading_gif.webp" />
        </span>
        <div class="modal__btns">
            <button id="educateAdd" class="modal__btn modal__btn--apply" type="button">Add</button>
            <button id="educateAddAddDismiss" class="modal__btn modal__btn--dismiss skillDissmisClick" type="button">Dismiss</button>
        </div>
    </div>
    <!-- end modal add -->
    <!-- modal edit -->
    <div id="modal-edit-educateAdd" class="zoom-anim-dialog mfp-hide modal">
        <h6 class="modal__title">Edit Skill</h6>

        <label class="form__label">Skill Name</label>
        <input id="EducateEditName" name="EducateEditName" class="form__input">

        <label class="form__label">Skill Value</label>
        <input type="number" id="EducateEditValue" name="EducateEditValue" class="form__input">
        <div id="edit-educate-error">
        </div>
        <span class="d-none" id="spinner">
            <img style="width:20px" src="~/loading_gif.webp" />
        </span>
        <div class="modal__btns">
            <button id="educateEdit" class="modal__btn modal__btn--apply" type="button">Save</button>
            <button id="educateAddDismiss" class="modal__btn modal__btn--dismiss skillDissmisClick" type="button">Dismiss</button>
        </div>
    </div>
    <!-- end modal edit -->
    <!-- modal delete -->
    <div id="modal-delete" class="zoom-anim-dialog mfp-hide modal">
        <h6 class="modal__title">Skill delete</h6>

        <p class="modal__text">Are you sure to permanently delete this skill?</p>

        <div class="modal__btns">
            <button id="skillDelete" class="modal__btn modal__btn--apply" type="button">Delete</button>
            <button class="modal__btn modal__btn--dismiss" type="button">Dismiss</button>
        </div>
    </div>
    <!-- end modal delete -->
</div>

@section Scripts {
    <script src="~/js/Resume/Education/EditEducation.js"></script>
}

MyBlog.WebUI/Views/Resume/ExperienceEdit.cshtml
@model MyBlog.WebUI.Models.Resume.ExperienceViewModel

@{
    ViewData["Title"] = "ExperienceEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="main__title">
            <h2>About (Edit)</h2>
        </div>
    </div>
    <div class="col-12">
        <form action="edit" method="post" class="form" enctype="multipart/form-data" novalidate>
            <div asp-validation-summary="ModelOnly" class="model-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="row row--form">


                <div class="col-12 col-md-7 form__content">
                    <div class="row row--form">
                        <div class="col-12">
                            <label asp-for="Title" class="form__label"></label>
                            <input asp-for="Title" class="form__input" placeholder="Title Giriniz">
                            <span asp-validation-for="Title" class="model-danger"></span>
                        </div>

                        <div class="col-12">
                            <label asp-for="DateBetween" class="form__label"></label>
                            <input asp-for="DateBetween" class="form__input" placeholder="Hangi tarihler arasında">
                            <span asp-validation-for="DateBetween" class="model-danger"></span>
                        </div>
                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="CompanyName" class="form__label"></label>
                            <input asp-for="CompanyName" class="form__input" placeholder="Email">
                            <span asp-validation-for="CompanyName" class="model-danger"></span>
                        </div>
                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="Adress" class="form__label"></label>
                            <input asp-for="Adress" class="form__input" placeholder="Adres">
                            <span asp-validation-for="Adress" class="model-danger"></span>
                        </div>
                        <div class="col-12 col-sm-6 col-lg-3">
                            <label asp-for="DisplayOrder" class="form__label"></label>
                            <input asp-for="DisplayOrder" type="number" min="1" class="form__input" placeholder="DisplayOrder">
                            <span asp-validation-for="DisplayOrder" class="model-danger"></span>
                        </div>


                        <div class="col-12">
                            <label asp-for="ExperienceSteps" class="form__label"></label>
                            <textarea asp-for="ExperienceSteps" class="form__textarea" placeholder="Deneyim Adımları"></textarea>
                            <span asp-validation-for="ExperienceSteps" class="model-danger"></span>
                        </div>



                    </div>
                </div>

                <div class="col-12">
                    <button type="submit" class="form__btn">Save</button>
                </div>
            </div>
        </form>
    </div>

    <div id="modal-delete" class="zoom-anim-dialog mfp-hide modal">
        <h6 class="modal__title">Skill delete</h6>

        <p class="modal__text">Are you sure to permanently delete this skill?</p>

        <div class="modal__btns">
            <button id="skillDelete" class="modal__btn modal__btn--apply" type="button">Delete</button>
            <button class="modal__btn modal__btn--dismiss" type="button">Dismiss</button>
        </div>
    </div>
</div>

MyBlog.WebUI/Views/Resume/Experiences.cshtml
@model List<MyBlog.WebUI.Models.Resume.ExperienceViewModel>

@{
    ViewData["Title"] = "Experiences";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="main__title">
            <h2>Experiences (Edit)</h2>
        </div>
    </div>

    <div class="col-12">
        <form action="edit" method="post" class="form" enctype="multipart/form-data" novalidate>
            <div asp-validation-summary="ModelOnly" class="model-danger"></div>
            <input type="hidden" />
            <div class="row row--form">
                <div class="col-12 col-md-7 form__content">
                    <h4 class="form__title">Experiences</h4>
                    <a asp-controller="Resume" asp-action="CreateExperience" class="form__btn ml-0 mb-3">Add Experience</a>
                    <div class="main__table-wrap mCustomScrollbar _mCS_2 mCS_no_scrollbar" style="overflow: visible;">
                        <div id="mCSB_2" class="mCustomScrollBox mCS-custom-bar2 mCSB_horizontal mCSB_outside" tabindex="0" style="max-height: none;">
                            <div id="mCSB_2_container" class="mCSB_container mCS_x_hidden mCS_no_scrollbar_x" style="position: relative; top: 0px; left: 0px; width: 1051px; min-width: 100%; overflow-x: inherit;" dir="ltr">
                                <table class="main__table">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Date</th>
                                            <th>Order</th>
                                            <th>ACTIONS</th>
                                        </tr>
                                    </thead>

                                    <tbody id="eduTbody">
                                        @foreach (var exp in Model)
                                        {

                                            <tr id="tr_@exp.Id">

                                                <td>
                                                    <div class="main__table-text">@exp.Id</div>
                                                </td>
                                                <td>
                                                    <div class="main__table-text">@exp.Title</div>
                                                </td>
                                                <td>
                                                    <div class="main__table-text">@exp.DateBetween</div>
                                                </td>
                                                <td>
                                                    <div class="main__table-text">@exp.DisplayOrder</div>
                                                </td>

                                                <td>
                                                    <div class="main__table-btns">
                                                        <a asp-controller="Resume" asp-action="ExperienceEdit" asp-route-id="@exp.Id" class="main__table-btn main__table-btn--edit ">
                                                            <i class="icon ion-ios-create "></i>
                                                        </a>
                                                        <a href="#modal-delete" id="@exp.Id" class="main__table-btn main__table-btn--delete opening_modal_delete open-modal">
                                                            <i class="icon ion-ios-trash"></i>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        }


                                    </tbody>
                                </table>
                            </div>
                        </div><div id="mCSB_2_scrollbar_horizontal" class="mCSB_scrollTools mCSB_2_scrollbar mCS-custom-bar2 mCSB_scrollTools_horizontal" style="display: none;"><div class="mCSB_draggerContainer"><div id="mCSB_2_dragger_horizontal" class="mCSB_dragger" style="position: absolute; min-width: 30px; width: 0px; left: 0px;"><div class="mCSB_dragger_bar"></div><div class="mCSB_draggerRail"></div></div></div></div>
                    </div>
                </div>

            </div>
        </form>
    </div>

    <!-- modal delete -->
    <div id="modal-delete" class="zoom-anim-dialog mfp-hide modal">
        <h6 class="modal__title">Experience delete</h6>
        <div id="delete-exp-error">
        </div>
        <p class="modal__text">Are you sure to permanently delete this experience?</p>

        <div class="modal__btns">
            <button id="expDelete" class="modal__btn modal__btn--apply" type="button">Delete</button>
            <button class="modal__btn modal__btn--dismiss skillDissmisClick" type="button">Dismiss</button>
        </div>
    </div>
    <!-- end modal delete -->

</div>


@section Scripts {
    <environment names="Development">
        <script src="resume-experience" debug="true"></script>
    </environment>

    <environment names="Production">
        <script src="resume-experience"></script>
    </environment>
}